version: "3.8"

services:
  db:
    # image: ghcr.io/inso-tuwien/binocular-database:latest
    image: ghcr.io/inso-tuwien/binocular-database:6773404196
    container_name: binocular_db
    restart: unless-stopped
    ports:
      - "8529:8529"

  binocular-init:
    # image: ghcr.io/inso-tuwien/binocular-backend:latest
    # image: ghcr.io/inso-tuwien/binocular-backend:latest-local
    image: ghcr.io/inso-tuwien/binocular-backend:6812925569
    depends_on:
      - db
    container_name: "binocular_init"
    # user: "root"
    tty: true
    environment:
      - DEBUG=idx*,importer*,git*,db*,context*
    command:
      [
        "tsx",
        "binocular.js",
        "--no-open",
        "--no-server",
        # "/app/binocular/repo/test-repo"
        "/app/binocular/repo/23ws-ase-pr-inso-06"
      ]
    volumes:
      - type: bind
        source: .binocularrc_sepm_ws23
        target: /app/binocular/repo/23ws-ase-pr-inso-06/.binocularrc
        read_only: true
      - type: bind
        source: .binocularrc
        target: /app/binocular/repo/test-repo/.binocularrc
        read_only: true
      - ./:/app/binocular/repo/test-repo
      # - ./binocular-backend/context.js:/app/binocular/binocular-backend/context.js
      # - ./binocular.js:/app/binocular/binocular.js
      # - ./binocular-frontend/config/context.json:/app/binocular/binocular-backend/../binocular-frontend/config/context.json
      # - ./gitlab.json:/app/binocular/binocular-frontend/config/gitlab.json
      - /Users/rise/Repositories/SEPM_WS23/23ws-ase-pr-inso-06:/app/binocular/repo/23ws-ase-pr-inso-06


  binocular:
    container_name: binocular_app
    image: ghcr.io/inso-tuwien/binocular-frontend:latest
    ports:
      - 8088:80
