name: "Docker Setup"
description: "Shared Steps for setting up docker build and caching"

inputs:
  registry_url:
    description: “URL for image registry”
    required: true
  registry_username:
    description: “Username for image registry”
    required: true
  registry_password:
    description: “Password for image registry”
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      shell: bash
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.registry_url }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Set up Builder Buildx
      shell: bash
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      shell: bash
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: ${{ runner.os }}-buildx-
