# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language.service.proto

require 'google/protobuf'

require 'registration.message_pb'
require 'language.message_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("language.service.proto", :syntax => :proto3) do
  end
end

module Binocular
  module Comm
  end
end
