# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language.message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("language.message.proto", :syntax => :proto3) do
    add_message "binocular.comm.Language" do
      optional :name, :string, 1
      optional :shortName, :string, 2
    end
    add_message "binocular.comm.LanguageDetectionRequest" do
      optional :token, :string, 1
      optional :path, :string, 2
      optional :content, :string, 3
    end
  end
end

module Binocular
  module Comm
    Language = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.Language").msgclass
    LanguageDetectionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.LanguageDetectionRequest").msgclass
  end
end
