# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: language.service.proto for package 'binocular.comm'

require 'grpc'
require 'language.service_pb'

module Binocular
  module Comm
    module LanguageDetectionService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'binocular.comm.LanguageDetectionService'

        # service gets disconnected by the gateway
        rpc :disconnect, UnregisterRequest, UnregisterResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
