# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registration.message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("registration.message.proto", :syntax => :proto3) do
    add_message "binocular.comm.Client" do
      optional :address, :string, 1
      optional :port, :uint32, 2
    end
    add_message "binocular.comm.RegistrationRequest" do
      optional :client, :message, 1, "binocular.comm.Client"
      optional :type, :enum, 2, "binocular.comm.ServiceType"
    end
    add_message "binocular.comm.RegistrationResponse" do
      optional :token, :string, 1
    end
    add_message "binocular.comm.UnregisterRequest" do
      optional :token, :string, 1
    end
    add_message "binocular.comm.UnregisterResponse" do
    end
    add_message "binocular.comm.HeartbeatRequest" do
      optional :token, :string, 1
    end
    add_message "binocular.comm.EmptyResponse" do
    end
    add_enum "binocular.comm.ServiceType" do
      value :None, 0
      value :LanguageDetectionService, 1
    end
  end
end

module Binocular
  module Comm
    Client = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.Client").msgclass
    RegistrationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.RegistrationRequest").msgclass
    RegistrationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.RegistrationResponse").msgclass
    UnregisterRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.UnregisterRequest").msgclass
    UnregisterResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.UnregisterResponse").msgclass
    HeartbeatRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.HeartbeatRequest").msgclass
    EmptyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.EmptyResponse").msgclass
    ServiceType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("binocular.comm.ServiceType").enummodule
  end
end
