env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - prettier
  - lambdas
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2020
  sourceType: 'module'
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      printWidth: 140
  no-console: off
  indent: ['error', 2, { "SwitchCase": 1 }]
  max-len: ["error", { "code": 140 }]
  comma-dangle: ["error", "only-multiline"]
  operator-linebreak: ['error', 'after', { "overrides": { "?": "before", ":": "before"} }]
  linebreak-style: ["error", "unix"]
  quotes:
    - error
    - single
    - avoidEscape: true
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-this-alias': 0
  '@typescript-eslint/no-explicit-any': 0
  prefer-rest-params: 0
plugins:
  - prettier
