name: Run Unit-Tests

on:
  pull_request:
    branches:
      - develop

#env: set env if needed

jobs:

  test-server:

    runs-on: ubuntu-latest
    services:

      arangodb:
        image: arangodb:3.11
        ports:
          - 8529:8529
        env:
          ARANGO_ROOT_PASSWORD: openSesame

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set .pupilrc variables
        uses: microsoft/variable-substitution@v1
        with:
          files: .binocularrc_ci
        env:
          github.auth.token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename binocularrc
        run: mv .binocularrc_ci .binocularrc

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests backend
        run: npm run test:backend
  
  test-ui:
    runs-on: ubuntu-latest
    # services:
    #   arangodb:
    #     image: arangodb:3.11
    #     ports:
    #       - 8529:8529
    #     env:
    #       ARANGO_ROOT_PASSWORD: openSesame

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set .pupilrc variables
        uses: microsoft/variable-substitution@v1
        with:
          files: .binocularrc_ci
        env:
          github.auth.token: ${{ secrets.GITHUB_TOKEN }}

      - name: Rename binocularrc
        run: mv .binocularrc_ci .binocularrc

      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
            
      - name: Run tests frontend
        run: npm run test:frontend

    # - name: Collect coverage
    #   run: npm run coverage
